# Generated by Django 2.0 on 2018-08-23 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
                ('date_of_birth', models.CharField(max_length=30)),
                ('distance_unit', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('height_unit', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('weight_unit', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
